name: gym_app
description: 'A new Flutter project.'
publish_to: 'none' # No publicar en pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_auth: ^5.5.2
  firebase_ui_auth: ^1.14.0
  provider: ^6.1.4
  intl: ^0.19.0
  uuid: ^4.5.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^3.5.0
  qr_flutter: ^4.1.0
  url_launcher: ^6.3.1
  firebase_auth_mocks: ^0.14.1
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  fake_cloud_firestore: ^3.1.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/gym_logo.png
    - assets/memberships/
    - assets/workouts/
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/gym_logo.png'
